---
# COPY and rename this file to secrets.yml and modify as needed
development:
  DATABASE_URL: sqlite://backend_app/db/store/development.db

test:
  DATABASE_URL: sqlite://backend_app/db/store/test.db
  
production:
  DATABASE_URL: postgres://user:password@host:port/database
